name: Build and deploy Node.js app to Azure Web App - hello-trello

on:
  push:
    branches:
      - azure_app
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Prepare app for deployment
        run: |
          mkdir -p deploy/.next
          cp -r .next/standalone/* deploy/
          cp -r .next/static deploy/.next/static
          cp server.js deploy/server.js
          cp next.config.js deploy/next.config.js
          cp package.json deploy/package.json


      - name: Zip artifact for deployment
        run: |
          cd deploy
          zip -r ../release.zip .

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_92784B99509C4547B71B430269A08B7D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E04E6197D45C47008FC583A4D379E9F3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E4FF6510A009416797CEC476F5914E33 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'hello-trello'
          slot-name: 'Production'
          package: .
